export interface CityOption {
  name: string
  county: 'Miami-Dade' | 'Broward' | 'Palm Beach'
}

export const SOUTH_FLORIDA_CITIES: CityOption[] = [
  // Broward (primary market — listed first)
  { name: 'Fort Lauderdale',    county: 'Broward' },
  { name: 'Hollywood',          county: 'Broward' },
  { name: 'Pembroke Pines',     county: 'Broward' },
  { name: 'Miramar',            county: 'Broward' },
  { name: 'Coral Springs',      county: 'Broward' },
  { name: 'Pompano Beach',      county: 'Broward' },
  { name: 'Sunrise',            county: 'Broward' },
  { name: 'Plantation',         county: 'Broward' },
  { name: 'Lauderhill',         county: 'Broward' },
  { name: 'Weston',             county: 'Broward' },
  { name: 'Davie',              county: 'Broward' },
  { name: 'Deerfield Beach',    county: 'Broward' },
  { name: 'Hallandale Beach',   county: 'Broward' },
  { name: 'Oakland Park',       county: 'Broward' },
  { name: 'Tamarac',            county: 'Broward' },
  { name: 'Margate',            county: 'Broward' },
  { name: 'North Lauderdale',   county: 'Broward' },
  { name: 'Coconut Creek',      county: 'Broward' },
  { name: 'Lauderdale Lakes',   county: 'Broward' },
  { name: 'Parkland',           county: 'Broward' },
  { name: 'Wilton Manors',      county: 'Broward' },
  { name: 'Cooper City',        county: 'Broward' },
  { name: 'Dania Beach',        county: 'Broward' },
  { name: 'Lighthouse Point',   county: 'Broward' },

  // Miami-Dade
  { name: 'Miami',              county: 'Miami-Dade' },
  { name: 'Miami Beach',        county: 'Miami-Dade' },
  { name: 'Hialeah',            county: 'Miami-Dade' },
  { name: 'Coral Gables',       county: 'Miami-Dade' },
  { name: 'Doral',              county: 'Miami-Dade' },
  { name: 'Homestead',          county: 'Miami-Dade' },
  { name: 'Miami Gardens',      county: 'Miami-Dade' },
  { name: 'North Miami',        county: 'Miami-Dade' },
  { name: 'North Miami Beach',  county: 'Miami-Dade' },
  { name: 'Aventura',           county: 'Miami-Dade' },
  { name: 'Kendall',            county: 'Miami-Dade' },
  { name: 'Cutler Bay',         county: 'Miami-Dade' },
  { name: 'Palmetto Bay',       county: 'Miami-Dade' },
  { name: 'Pinecrest',          county: 'Miami-Dade' },
  { name: 'South Miami',        county: 'Miami-Dade' },
  { name: 'Sweetwater',         county: 'Miami-Dade' },
  { name: 'Miami Shores',       county: 'Miami-Dade' },
  { name: 'Opa-locka',          county: 'Miami-Dade' },
  { name: 'Bal Harbour',        county: 'Miami-Dade' },
  { name: 'Bay Harbor Islands', county: 'Miami-Dade' },
  { name: 'Key Biscayne',       county: 'Miami-Dade' },
  { name: 'Brickell',           county: 'Miami-Dade' },
  { name: 'Wynwood',            county: 'Miami-Dade' },
  { name: 'Little Havana',      county: 'Miami-Dade' },
  { name: 'Edgewater',          county: 'Miami-Dade' },

  // Palm Beach
  { name: 'West Palm Beach',    county: 'Palm Beach' },
  { name: 'Boca Raton',         county: 'Palm Beach' },
  { name: 'Delray Beach',       county: 'Palm Beach' },
  { name: 'Boynton Beach',      county: 'Palm Beach' },
  { name: 'Lake Worth Beach',   county: 'Palm Beach' },
  { name: 'Palm Beach Gardens', county: 'Palm Beach' },
  { name: 'Wellington',         county: 'Palm Beach' },
  { name: 'Jupiter',            county: 'Palm Beach' },
  { name: 'Greenacres',         county: 'Palm Beach' },
  { name: 'Royal Palm Beach',   county: 'Palm Beach' },
  { name: 'Riviera Beach',      county: 'Palm Beach' },
  { name: 'Palm Springs',       county: 'Palm Beach' },
  { name: 'Lantana',            county: 'Palm Beach' },
  { name: 'Belle Glade',        county: 'Palm Beach' },
  { name: 'North Palm Beach',   county: 'Palm Beach' },
  { name: 'Palm Beach',         county: 'Palm Beach' },
  { name: 'Lake Clarke Shores', county: 'Palm Beach' },
  { name: 'Manalapan',          county: 'Palm Beach' },
]

export const COUNTY_COLORS: Record<string, string> = {
  'Miami-Dade': '#388bfd',
  'Broward':    '#a371f7',
  'Palm Beach': '#3fb950',
}
